version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
      - 9229:9229
    networks:
      - postgres
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4  
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres

volumes:
  db_data:
  pgadmin:

networks:
  postgres:
    driver: bridge    